FROM maven:3.8-amazoncorretto-11 as builder
WORKDIR /app
COPY . /app
RUN mvn package -DskipTests

FROM openjdk:11-slim
COPY --from=builder /app/target/*.jar /home/app/myapp.jar
#COPY target/*.jar /home/app/customer-support.jar
ENTRYPOINT ["java", "-jar", "/home/app/myapp.jar", "--spring-profiles.active=docker"]