# FROM node:19-alpine as builder
# WORKDIR /app
# COPY . /app
# RUN npm install && npm run build

# FROM nginx:1.21.5
# COPY --from=builder app/dist /usr/share/nginx/html

FROM nginx:1.21.5
COPY dist /usr/share/nginx/html