FROM maven:3.8-amazoncorretto-17 as builder
WORKDIR /app
COPY . /app
RUN mvn package -DskipTests

FROM amazoncorretto:17.0.6
COPY --from=builder /app/target/*.jar /home/app/myapp.jar
#COPY target/*.jar /home/app/recommendation.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=docker", "-jar", "/home/app/myapp.jar"]